name: torchmd-net
channels:
  - conda-forge
dependencies:
  - h5py
  - matplotlib-base
  - nnpops
  - pip
  - pytorch
  - pytorch_geometric
  - lightning
  - pydantic
  - torchmetrics
  - tqdm
  # Dev tools
  - flake8
  - pytest
  - psutil
  - gxx
