load_model: null

# training settings
num_epochs: 300
lr_warmup_steps: 5000
lr: 0.0002
lr_patience: 5
lr_min: 1.e-07
lr_factor: 0.8
weight_decay: 0.0
early_stopping_patience: 30
loss_type: MAE
loss_scale_y: 1.0
loss_scale_dy: 1.0
energy_weight: 1.0
force_weight: 1.0

# dataset specific
dataset: Molecule3D
dataset_arg: null
dataset_root: /path/to/data
derivative: false
split_mode: random

# dataloader specific
reload: 1
batch_size: 32
inference_batch_size: 32
standardize: true
splits: null
train_size: null
val_size: null
test_size: null
num_workers: 12

# model architecture specific
model: ViSNetBlock
output_model: Scalar
prior_model: null

# architectural specific
embedding_dimension: 256
num_layers: 9
num_rbf: 32
activation: silu
rbf_type: expnorm
trainable_rbf: false
attn_activation: silu
num_heads: 8
cutoff: 5.0
max_z: 200
max_num_neighbors: 32
reduce_op: mean
lmax: 1
vecnorm_type: max_min
trainable_vecnorm: false
vertex_type: None

# other specific
ngpus: 16
num_nodes: 1
precision: 32
log_dir: /path/to/logs
task: train
seed: 1
distributed_backend: ddp
redirect: false
accelerator: gpu
test_interval: 10
save_interval: 1
